-- ===================
-- INSERCIÓN DE DATOS DE PRUEBA
-- ===================

-- Insertar 30 clientes
INSERT INTO clientes (nombre_completo, correo, telefono) VALUES
                                                             ('Juan Pérez García', 'juan.perez@email.com', '555-0101'),
                                                             ('María González López', 'maria.gonzalez@email.com', '555-0102'),
                                                             ('Carlos Sánchez Martínez', 'carlos.sanchez@email.com', '555-0103'),
                                                             ('Ana Rodríguez Hernández', 'ana.rodriguez@email.com', '555-0104'),
                                                             ('Luis Fernández Gómez', 'luis.fernandez@email.com', '555-0105'),
                                                             ('Laura Díaz Pérez', 'laura.diaz@email.com', '555-0106'),
                                                             ('Javier Alonso Ruiz', 'javier.alonso@email.com', '555-0107'),
                                                             ('Sofía Moreno Jiménez', 'sofia.moreno@email.com', '555-0108'),
                                                             ('David Álvarez Gutiérrez', 'david.alvarez@email.com', '555-0109'),
                                                             ('Elena Romero Navarro', 'elena.romero@email.com', '555-0110'),
                                                             ('Daniel Vázquez Ramos', 'daniel.vazquez@email.com', '555-0111'),
                                                             ('Paula Castro Castillo', 'paula.castro@email.com', '555-0112'),
                                                             ('Alejandro Ortega Gil', 'alejandro.ortega@email.com', '555-0113'),
                                                             ('Carmen Serrano Santos', 'carmen.serrano@email.com', '555-0114'),
                                                             ('Adrián Molina Marín', 'adrian.molina@email.com', '555-0115'),
                                                             ('Isabel Núñez Torres', 'isabel.nunez@email.com', '555-0116'),
                                                             ('Pablo Medina Soto', 'pablo.medina@email.com', '555-0117'),
                                                             ('Lucía Cano Vega', 'lucia.cano@email.com', '555-0118'),
                                                             ('Marcos Delgado León', 'marcos.delgado@email.com', '555-0119'),
                                                             ('Marta Reyes Prieto', 'marta.reyes@email.com', '555-0120'),
                                                             ('Sergio Gallego Vidal', 'sergio.gallego@email.com', '555-0121'),
                                                             ('Cristina Pascual Ibáñez', 'cristina.pascual@email.com', '555-0122'),
                                                             ('Jorge Herrero Peña', 'jorge.herrero@email.com', '555-0123'),
                                                             ('Raquel Crespo Soler', 'raquel.crespo@email.com', '555-0124'),
                                                             ('Óscar Rubio Blanco', 'oscar.rubio@email.com', '555-0125'),
                                                             ('Verónica Domínguez Ferrer', 'veronica.dominguez@email.com', '555-0126'),
                                                             ('Francisco Morales Moya', 'francisco.morales@email.com', '555-0127'),
                                                             ('Beatriz Parra Campos', 'beatriz.parra@email.com', '555-0128'),
                                                             ('Manuel Rivas Arias', 'manuel.rivas@email.com', '555-0129'),
                                                             ('Natalia Sanz Lorenzo', 'natalia.sanz@email.com', '555-0130');

-- Insertar 8 técnicos
INSERT INTO tecnicos (nombre_completo, especialidad) VALUES
                                                         ('Miguel Ángel Roca', 'Hardware'),
                                                         ('Beatriz Lorenzo Sanz', 'Hardware'),
                                                         ('Ricardo Fuentes Solís', 'Software'),
                                                         ('Mónica Beltrán Costa', 'Software'),
                                                         ('Óscar Gallardo Bravo', 'Redes'),
                                                         ('Lorena Pardo Flores', 'Redes'),
                                                         ('Héctor Villa Duran', 'Software'),
                                                         ('Susana Aguilera Cruz', 'Hardware');

-- Insertar 50 tickets
-- Estados: 1: Abierto, 2: En proceso, 3: Cerrado
-- Tipos de servicio: 1: Hardware, 2: Software, 3: Redes
INSERT INTO tickets (id_cliente, id_tipo_servicio, fecha_solicitud, id_tecnico, id_estado, fecha_asignacion, fecha_cierre, diagnostico, solucion) VALUES
                                                                                                                                                      (1, 1, '2023-10-01', 1, 3, '2023-10-02', '2023-10-05', 'El disco duro principal presenta fallos de lectura.', 'Se reemplazó el disco duro por un SSD de 512GB y se reinstaló el sistema operativo.'),
                                                                                                                                                      (2, 2, '2023-10-03', 3, 3, '2023-10-03', '2023-10-04', 'El software de contabilidad no se inicia.', 'Se actualizaron las librerías del sistema y se reinstaló el software. Funciona correctamente.'),
                                                                                                                                                      (3, 3, '2023-10-05', 5, 2, '2023-10-06', NULL, 'La conexión a internet es intermitente en el área de ventas.', NULL),
                                                                                                                                                      (4, 1, '2023-10-06', 2, 3, '2023-10-07', '2023-10-10', 'La pantalla del portátil no enciende.', 'Se detectó un fallo en el inversor de la pantalla. Se procedió a su cambio.'),
                                                                                                                                                      (5, 2, '2023-10-08', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (6, 3, '2023-10-10', 6, 3, '2023-10-11', '2023-10-15', 'No hay acceso a la impresora de red desde el departamento de marketing.', 'El firewall estaba bloqueando el puerto de la impresora. Se creó una regla de excepción.'),
                                                                                                                                                      (7, 1, '2023-10-12', 8, 2, '2023-10-13', NULL, 'El ordenador se reinicia de forma aleatoria.', NULL),
                                                                                                                                                      (8, 2, '2023-10-14', 4, 3, '2023-10-14', '2023-10-16', 'Error de licencia en Microsoft Office.', 'Se reactivó la licencia de Office 365 con las credenciales corporativas.'),
                                                                                                                                                      (9, 3, '2023-10-15', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (10, 1, '2023-10-16', 1, 3, '2023-10-17', '2023-10-20', 'El teclado no responde en algunas teclas.', 'Se realizó una limpieza profunda y se solucionó el problema. Era suciedad acumulada.'),
                                                                                                                                                      (11, 2, '2023-11-01', 7, 2, '2023-11-02', NULL, 'El sistema operativo va muy lento.', NULL),
                                                                                                                                                      (12, 3, '2023-11-03', 5, 3, '2023-11-03', '2023-11-06', 'Necesitan configurar una nueva VPN para un teletrabajador.', 'Se configuró el cliente VPN en el equipo del usuario y se probó el acceso remoto.'),
                                                                                                                                                      (13, 1, '2023-11-05', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (14, 2, '2023-11-07', 3, 3, '2023-11-08', '2023-11-09', 'Imposible instalar la última actualización de Windows.', 'Se liberó espacio en el disco y se ejecutó el solucionador de problemas de Windows Update.'),
                                                                                                                                                      (15, 3, '2023-11-10', 6, 2, '2023-11-11', NULL, 'La velocidad de la red WiFi es muy baja.', NULL),
                                                                                                                                                      (16, 1, '2023-11-12', 2, 3, '2023-11-13', '2023-11-15', 'La batería del portátil dura menos de una hora.', 'Se reemplazó la batería por una nueva original.'),
                                                                                                                                                      (17, 2, '2023-11-14', 4, 2, '2023-11-15', NULL, 'Aparecen pop-ups y publicidad no deseada en el navegador.', NULL),
                                                                                                                                                      (18, 3, '2023-11-16', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (19, 1, '2023-11-18', 8, 3, '2023-11-20', '2023-11-22', 'El ratón USB no es detectado por el sistema.', 'Se probaron varios puertos y se determinó que el ratón estaba defectuoso. Se sustituyó.'),
                                                                                                                                                      (20, 2, '2023-11-21', 7, 3, '2023-11-21', '2023-11-23', 'El correo electrónico no sincroniza los mensajes nuevos.', 'Se eliminó y se volvió a configurar el perfil de Outlook. Problema solucionado.'),
                                                                                                                                                      (21, 3, '2024-01-05', 5, 2, '2024-01-08', NULL, 'No se puede acceder a la carpeta compartida del servidor.', NULL),
                                                                                                                                                      (22, 1, '2024-01-09', 1, 3, '2024-01-10', '2024-01-12', 'El ventilador de la CPU hace mucho ruido.', 'Limpieza del disipador y ventilador, y cambio de pasta térmica.'),
                                                                                                                                                      (23, 2, '2024-01-11', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (24, 3, '2024-01-15', 6, 3, '2024-01-16', '2024-01-18', 'Configuración de un nuevo punto de acceso inalámbrico.', 'Se instaló y configuró un AP en la zona de almacén para mejorar la cobertura.'),
                                                                                                                                                      (25, 1, '2024-01-20', 2, 2, '2024-01-22', NULL, 'El proyector no muestra la imagen del portátil.', NULL),
                                                                                                                                                      (26, 2, '2024-01-23', 3, 3, '2024-01-24', '2024-01-25', 'El antivirus reporta una amenaza pero no puede eliminarla.', 'Se ejecutó una herramienta de limpieza en modo seguro y se eliminó el malware.'),
                                                                                                                                                      (27, 3, '2024-01-28', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (28, 1, '2024-02-01', 8, 3, '2024-02-02', '2024-02-05', 'Se necesita ampliar la memoria RAM de un equipo de diseño.', 'Se instalaron 16GB de RAM adicionales, pasando de 16GB a 32GB.'),
                                                                                                                                                      (29, 2, '2024-02-04', 4, 2, '2024-02-05', NULL, 'El usuario olvidó su contraseña de Windows.', NULL),
                                                                                                                                                      (30, 3, '2024-02-06', 5, 3, '2024-02-07', '2024-02-09', 'Un cable de red está dañado y necesita ser reemplazado.', 'Se crimpó un nuevo cable de red de 5 metros y se instaló en el puesto del usuario.'),
                                                                                                                                                      (1, 2, '2024-02-10', 7, 2, '2024-02-12', NULL, 'El programa de diseño gráfico se cierra inesperadamente.', NULL),
                                                                                                                                                      (5, 1, '2024-02-12', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (15, 3, '2024-02-15', 6, 3, '2024-02-16', '2024-02-20', 'La velocidad de la red WiFi era muy baja.', 'Se cambió el canal de emisión del router para evitar interferencias.'),
                                                                                                                                                      (20, 1, '2024-02-18', 1, 2, '2024-02-19', NULL, 'La impresora no toma el papel de la bandeja.', NULL),
                                                                                                                                                      (25, 2, '2024-02-22', 3, 3, '2024-02-23', '2024-02-26', 'El proyector no mostraba la imagen del portátil.', 'El problema era el cable HDMI. Se reemplazó por uno nuevo.'),
                                                                                                                                                      (3, 2, '2024-03-01', 4, 3, '2024-03-01', '2024-03-04', 'La firma digital no es reconocida por el sistema de Hacienda.', 'Se reinstalaron los certificados raíz y el problema quedó resuelto.'),
                                                                                                                                                      (9, 3, '2024-03-05', 5, 2, '2024-03-06', NULL, 'Necesitan dar de alta un nuevo usuario en la red.', NULL),
                                                                                                                                                      (12, 1, '2024-03-08', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (18, 2, '2024-03-10', 7, 3, '2024-03-11', '2024-03-12', 'No se pueden guardar documentos en la unidad de red.', 'El usuario no tenía permisos de escritura en la carpeta. Se ajustaron los permisos.'),
                                                                                                                                                      (22, 3, '2024-03-14', 6, 2, '2024-03-15', NULL, 'La conexión a la base de datos es muy lenta desde una de las sucursales.', NULL),
                                                                                                                                                      (27, 1, '2024-03-18', 2, 3, '2024-03-19', '2024-03-21', 'La webcam integrada no funciona.', 'Se actualizaron los drivers desde la web del fabricante y se solucionó.'),
                                                                                                                                                      (4, 2, '2024-03-20', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (8, 3, '2024-03-22', 5, 3, '2024-03-25', '2024-03-27', 'Pérdida de paquetes al hacer ping al router principal.', 'Se detectó un switch defectuoso en la red y fue reemplazado.'),
                                                                                                                                                      (14, 1, '2024-03-25', 8, 2, '2024-03-26', NULL, 'El equipo emite pitidos al arrancar y no da video.', NULL),
                                                                                                                                                      (19, 2, '2024-04-01', 4, 3, '2024-04-02', '2024-04-03', 'El usuario no puede acceder a su archivo de correos antiguos (.pst).', 'Se reparó el archivo .pst con la herramienta SCANPST.exe.'),
                                                                                                                                                      (24, 1, '2024-04-04', NULL, 1, NULL, NULL, NULL, NULL),
                                                                                                                                                      (29, 3, '2024-04-08', 6, 2, '2024-04-09', NULL, 'Configurar el acceso a una nueva impresora multifunción.', NULL),
                                                                                                                                                      (7, 2, '2024-04-10', 7, 3, '2024-04-11', '2024-04-15', 'El ordenador se reiniciaba de forma aleatoria.', 'El diagnóstico reveló un módulo de RAM defectuoso. Fue sustituido.'),
                                                                                                                                                      (11, 1, '2024-04-12', 1, 3, '2024-04-15', '2024-04-18', 'El sistema operativo iba muy lento.', 'Se realizó una optimización del sistema, desfragmentación y limpieza de malware.');
